"""Add password and persona fields

Revision ID: 76fa1d0bffbb
Revises: 
Create Date: 2026-02-27 19:29:09.941162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fa1d0bffbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('persona_type', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'persona_type')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
