"""Add micronutrients to recipe and cached_ingredients

Revision ID: 86a42807254c
Revises: 9e4d2d86ab46
Create Date: 2026-03-01 16:01:12.622129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86a42807254c'
down_revision: Union[str, None] = '9e4d2d86ab46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_grocery_items_name', table_name='grocery_items')
    op.drop_index('ix_grocery_items_user_id', table_name='grocery_items')
    op.drop_table('grocery_items')
    op.add_column('cached_ingredients', sa.Column('vitamin_c_mg', sa.Float(), nullable=True))
    op.add_column('cached_ingredients', sa.Column('iron_mg', sa.Float(), nullable=True))
    op.add_column('cached_ingredients', sa.Column('calcium_mg', sa.Float(), nullable=True))
    op.add_column('cached_ingredients', sa.Column('sodium_mg', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('vitamin_c_mg', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('iron_mg', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('calcium_mg', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('sodium_mg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'sodium_mg')
    op.drop_column('recipes', 'calcium_mg')
    op.drop_column('recipes', 'iron_mg')
    op.drop_column('recipes', 'vitamin_c_mg')
    op.drop_column('cached_ingredients', 'sodium_mg')
    op.drop_column('cached_ingredients', 'calcium_mg')
    op.drop_column('cached_ingredients', 'iron_mg')
    op.drop_column('cached_ingredients', 'vitamin_c_mg')
    op.create_table('grocery_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_checked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_from_menu', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='grocery_items_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='grocery_items_pkey')
    )
    op.create_index('ix_grocery_items_user_id', 'grocery_items', ['user_id'], unique=False)
    op.create_index('ix_grocery_items_name', 'grocery_items', ['name'], unique=False)
    # ### end Alembic commands ###
