"""add recipes table

Revision ID: 9e4d2d86ab46
Revises: 4a684db580d7
Create Date: 2026-02-28 15:26:54.987761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e4d2d86ab46'
down_revision: Union[str, None] = '4a684db580d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('diet_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('meal_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
